# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb, '10000']
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language: python
        language_version: python3
        entry: black
        args: ['--config', 'pyproject.toml']
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.4
    hooks:
      - id: nbqa-black
        args: ['--config=pyproject.toml']
  - repo: local
    hooks:
      - id: flake8
        args: ['--config', 'pyproject.toml']
        name: flake8
        entry: flake8
        language: system
        types: [python]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["--config=pyproject.toml"]
        additional_dependencies: [".[toml]"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        verbose: true
        args: ['--show-error-codes', '--config-file', 'pyproject.toml']
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
