[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '/(\\.git|\\.hg|\\.mypy_cache|\\.tox|\\.venv|_build|buck-out|build|dist)/'

[nbqa.black]
line-length = 79

[tool.flake8]
ignore = ["E203", "E266", "E501", "W503", "F403", "F401"]
max-line-length = 79
max-complexity = 18
select = ["B", "C", "E", "F", "W", "T4", "B9"]

[tool.mypy]
ignore_missing_imports = true

[tool.bandit]
skips = ["B301", "B607", "B403", "B605"]
